name: CI - Build & Test

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: List root files
        run: ls -al

      # ---- ROOT ----
      - name: Install root dependencies
        run: npm install

      - name: Run backend tests
        run: npm test --if-present

      # ---- FRONTEND ----
      - name: List frontend files
        run: ls -al frontend

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build
